### PR TITLE
Add a 'join' func to the template engine

### PR DESCRIPTION
**Pull request by mikepea**
I needed this so that I can display JIRA labels in my 'list' template, but it should be generally useful.

Happy to have this pushed back for a more robust implementation with tests.

### CODE REVIEW

**Comment by mikepea** [comment]
Note that to enable displaying labels in 'list' output, you need to append to queryfields:

    queryfields: "summary,created,updated,priority,status,reporter,assignee,labels"

**Comment by coryb** [comment]
Looks good.  An alternative to using join would be something like this:
```
labels: {{ range .fields.labels }}
  - {{ . }}{{end}}
```
and just iterate over the labels and print them out, one per line.
-Cory

**Comment by coryb** [comment]
Oh, I see, you wanted this for "list", I was thinking "view", so you obviously don't want to print multiline stuff in "list".   So ignore my comment :)

Thanks,
-Cory

**Comment by lvh** [comment]
Uh, how do I use this? I tried to do the following:

```yaml
  - name: search
    help: search for text
    script: echo jira list --query='text ~ \"{{ join " " args.ARGS }}\"'
    args:
      - name: ARGS
        repeat: true
```

But got: `ERROR Invalid Usage: template: gojira:1:45: executing "gojira" at <args>: wrong type for value; expected []interface {}; got []string`

**Pull request merged**
