### PR TITLE
Allow overriding resolution

### PR DESCRIPTION
**Pull request by gvol**
I'm _not_ advocating that this be the way to solve #121, but it works for me and sometimes it's helpful to have a patch, even a bad one.  :-)

### CODE REVIEW

**Comment by coryb** [comment]
Thanks for this, I am swamped now and really appreciate the help.  I think your solution is reasonable, but I wonder if it would just make more sense to expose a `--resolution` option instead?  That would preserve the existing logic, and require just adding this to the usage function:
```
cmd.Flag("resolution", "Set resolution on transition").StringVar(&opts.Resolution)
```

**Comment by gvol** [comment]
Sounds like a great idea.  I tested and it works (after I reverted my other changes).

**Comment by coryb** [comment]
released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.13

**Comment by Maratyz** [comment]
The resolution will be updated to "Done" only with state of "Finish" after I tried with a couple of transition state ("Start", "Reopen", "Wait for Response", "Pause"), e.g. `jira trans --resolution="Done" "Wait for Response" --noedit JIRA-123`. 

Is this intended design? 

I also tried `override` in this way `jira edit -o resolution="Done" --noedit JIRA-123`, and it does not work neither.

**Comment by coryb** [comment]
@Maratyz i am not a Jira admin so I could be wrong, but it sounds like your Jira admins have set up some non-standard workflows.  The Jira api will abide by the rules set up for your project by the workflows, and there is nothing that I know of to allow `go-jira` to bypass those workflows.  I think you can only set a resolution on a "final" state for the workflows, sounds like "Finish" is a final workflow state for your project.

**Comment by Maratyz** [comment]
HI @coryb , thanks for your reply, which is helpful for me to check further.

**Pull request merged**
